name: Linter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
    - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
      with:
        ruby-version: 3.4
        bundler-cache: true
    - name: Run Linter
      run: bundle exec rubocop --parallel
